/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as ApiSeoAuditRouteImport } from './routes/api.seo-audit'
import { Route as ApiRunScheduledPromptsRouteImport } from './routes/api.run-scheduled-prompts'
import { Route as ApiPromptAuditRouteImport } from './routes/api.prompt-audit'
import { Route as ApiProcessJobsRouteImport } from './routes/api.process-jobs'
import { Route as ApiGeneratePromptsRouteImport } from './routes/api.generate-prompts'
import { Route as ApiGenerateInsightsRouteImport } from './routes/api.generate-insights'
import { Route as ApiGenerateFixitRouteImport } from './routes/api.generate-fixit'
import { Route as AppProjectIdIndexRouteImport } from './routes/app.$projectId.index'
import { Route as AppProjectIdSeoAuditRouteImport } from './routes/app.$projectId.seo-audit'
import { Route as AppProjectIdResponsesRouteImport } from './routes/app.$projectId.responses'
import { Route as AppProjectIdReportsRouteImport } from './routes/app.$projectId.reports'
import { Route as AppProjectIdRankingsRouteImport } from './routes/app.$projectId.rankings'
import { Route as AppProjectIdPromptsRouteImport } from './routes/app.$projectId.prompts'
import { Route as AppProjectIdModelsRouteImport } from './routes/app.$projectId.models'
import { Route as AppProjectIdMentionsRouteImport } from './routes/app.$projectId.mentions'
import { Route as AppProjectIdInsightsRouteImport } from './routes/app.$projectId.insights'
import { Route as AppProjectIdContentRouteImport } from './routes/app.$projectId.content'
import { Route as AppProjectIdCompetitorsRouteImport } from './routes/app.$projectId.competitors'
import { Route as AppProjectIdCitationsRouteImport } from './routes/app.$projectId.citations'
import { Route as AppProjectIdAnalyticsRouteImport } from './routes/app.$projectId.analytics'
import { Route as ApiLlmsTxtProjectIdRouteImport } from './routes/api.llms-txt.$projectId'
import { Route as AppProjectIdToolsResearchRouteImport } from './routes/app.$projectId.tools.research'
import { Route as AppProjectIdToolsAnnotationsRouteImport } from './routes/app.$projectId.tools.annotations'
import { Route as AppProjectIdReportsSentimentRouteImport } from './routes/app.$projectId.reports.sentiment'
import { Route as AppProjectIdReportsReputationRouteImport } from './routes/app.$projectId.reports.reputation'
import { Route as AppProjectIdReportsMediaRouteImport } from './routes/app.$projectId.reports.media'
import { Route as AppProjectIdReportsFanoutRouteImport } from './routes/app.$projectId.reports.fanout'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const ApiSeoAuditRoute = ApiSeoAuditRouteImport.update({
  id: '/api/seo-audit',
  path: '/api/seo-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunScheduledPromptsRoute = ApiRunScheduledPromptsRouteImport.update({
  id: '/api/run-scheduled-prompts',
  path: '/api/run-scheduled-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromptAuditRoute = ApiPromptAuditRouteImport.update({
  id: '/api/prompt-audit',
  path: '/api/prompt-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessJobsRoute = ApiProcessJobsRouteImport.update({
  id: '/api/process-jobs',
  path: '/api/process-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePromptsRoute = ApiGeneratePromptsRouteImport.update({
  id: '/api/generate-prompts',
  path: '/api/generate-prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateInsightsRoute = ApiGenerateInsightsRouteImport.update({
  id: '/api/generate-insights',
  path: '/api/generate-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateFixitRoute = ApiGenerateFixitRouteImport.update({
  id: '/api/generate-fixit',
  path: '/api/generate-fixit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectIdIndexRoute = AppProjectIdIndexRouteImport.update({
  id: '/$projectId/',
  path: '/$projectId/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdSeoAuditRoute = AppProjectIdSeoAuditRouteImport.update({
  id: '/$projectId/seo-audit',
  path: '/$projectId/seo-audit',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdResponsesRoute = AppProjectIdResponsesRouteImport.update({
  id: '/$projectId/responses',
  path: '/$projectId/responses',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdReportsRoute = AppProjectIdReportsRouteImport.update({
  id: '/$projectId/reports',
  path: '/$projectId/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdRankingsRoute = AppProjectIdRankingsRouteImport.update({
  id: '/$projectId/rankings',
  path: '/$projectId/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdPromptsRoute = AppProjectIdPromptsRouteImport.update({
  id: '/$projectId/prompts',
  path: '/$projectId/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdModelsRoute = AppProjectIdModelsRouteImport.update({
  id: '/$projectId/models',
  path: '/$projectId/models',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdMentionsRoute = AppProjectIdMentionsRouteImport.update({
  id: '/$projectId/mentions',
  path: '/$projectId/mentions',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdInsightsRoute = AppProjectIdInsightsRouteImport.update({
  id: '/$projectId/insights',
  path: '/$projectId/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdContentRoute = AppProjectIdContentRouteImport.update({
  id: '/$projectId/content',
  path: '/$projectId/content',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdCompetitorsRoute = AppProjectIdCompetitorsRouteImport.update({
  id: '/$projectId/competitors',
  path: '/$projectId/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdCitationsRoute = AppProjectIdCitationsRouteImport.update({
  id: '/$projectId/citations',
  path: '/$projectId/citations',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdAnalyticsRoute = AppProjectIdAnalyticsRouteImport.update({
  id: '/$projectId/analytics',
  path: '/$projectId/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiLlmsTxtProjectIdRoute = ApiLlmsTxtProjectIdRouteImport.update({
  id: '/api/llms-txt/$projectId',
  path: '/api/llms-txt/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectIdToolsResearchRoute =
  AppProjectIdToolsResearchRouteImport.update({
    id: '/$projectId/tools/research',
    path: '/$projectId/tools/research',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectIdToolsAnnotationsRoute =
  AppProjectIdToolsAnnotationsRouteImport.update({
    id: '/$projectId/tools/annotations',
    path: '/$projectId/tools/annotations',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectIdReportsSentimentRoute =
  AppProjectIdReportsSentimentRouteImport.update({
    id: '/sentiment',
    path: '/sentiment',
    getParentRoute: () => AppProjectIdReportsRoute,
  } as any)
const AppProjectIdReportsReputationRoute =
  AppProjectIdReportsReputationRouteImport.update({
    id: '/reputation',
    path: '/reputation',
    getParentRoute: () => AppProjectIdReportsRoute,
  } as any)
const AppProjectIdReportsMediaRoute =
  AppProjectIdReportsMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => AppProjectIdReportsRoute,
  } as any)
const AppProjectIdReportsFanoutRoute =
  AppProjectIdReportsFanoutRouteImport.update({
    id: '/fanout',
    path: '/fanout',
    getParentRoute: () => AppProjectIdReportsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/generate-fixit': typeof ApiGenerateFixitRoute
  '/api/generate-insights': typeof ApiGenerateInsightsRoute
  '/api/generate-prompts': typeof ApiGeneratePromptsRoute
  '/api/process-jobs': typeof ApiProcessJobsRoute
  '/api/prompt-audit': typeof ApiPromptAuditRoute
  '/api/run-scheduled-prompts': typeof ApiRunScheduledPromptsRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/api/llms-txt/$projectId': typeof ApiLlmsTxtProjectIdRoute
  '/app/$projectId/analytics': typeof AppProjectIdAnalyticsRoute
  '/app/$projectId/citations': typeof AppProjectIdCitationsRoute
  '/app/$projectId/competitors': typeof AppProjectIdCompetitorsRoute
  '/app/$projectId/content': typeof AppProjectIdContentRoute
  '/app/$projectId/insights': typeof AppProjectIdInsightsRoute
  '/app/$projectId/mentions': typeof AppProjectIdMentionsRoute
  '/app/$projectId/models': typeof AppProjectIdModelsRoute
  '/app/$projectId/prompts': typeof AppProjectIdPromptsRoute
  '/app/$projectId/rankings': typeof AppProjectIdRankingsRoute
  '/app/$projectId/reports': typeof AppProjectIdReportsRouteWithChildren
  '/app/$projectId/responses': typeof AppProjectIdResponsesRoute
  '/app/$projectId/seo-audit': typeof AppProjectIdSeoAuditRoute
  '/app/$projectId/': typeof AppProjectIdIndexRoute
  '/app/$projectId/reports/fanout': typeof AppProjectIdReportsFanoutRoute
  '/app/$projectId/reports/media': typeof AppProjectIdReportsMediaRoute
  '/app/$projectId/reports/reputation': typeof AppProjectIdReportsReputationRoute
  '/app/$projectId/reports/sentiment': typeof AppProjectIdReportsSentimentRoute
  '/app/$projectId/tools/annotations': typeof AppProjectIdToolsAnnotationsRoute
  '/app/$projectId/tools/research': typeof AppProjectIdToolsResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/api/generate-fixit': typeof ApiGenerateFixitRoute
  '/api/generate-insights': typeof ApiGenerateInsightsRoute
  '/api/generate-prompts': typeof ApiGeneratePromptsRoute
  '/api/process-jobs': typeof ApiProcessJobsRoute
  '/api/prompt-audit': typeof ApiPromptAuditRoute
  '/api/run-scheduled-prompts': typeof ApiRunScheduledPromptsRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
  '/api/llms-txt/$projectId': typeof ApiLlmsTxtProjectIdRoute
  '/app/$projectId/analytics': typeof AppProjectIdAnalyticsRoute
  '/app/$projectId/citations': typeof AppProjectIdCitationsRoute
  '/app/$projectId/competitors': typeof AppProjectIdCompetitorsRoute
  '/app/$projectId/content': typeof AppProjectIdContentRoute
  '/app/$projectId/insights': typeof AppProjectIdInsightsRoute
  '/app/$projectId/mentions': typeof AppProjectIdMentionsRoute
  '/app/$projectId/models': typeof AppProjectIdModelsRoute
  '/app/$projectId/prompts': typeof AppProjectIdPromptsRoute
  '/app/$projectId/rankings': typeof AppProjectIdRankingsRoute
  '/app/$projectId/reports': typeof AppProjectIdReportsRouteWithChildren
  '/app/$projectId/responses': typeof AppProjectIdResponsesRoute
  '/app/$projectId/seo-audit': typeof AppProjectIdSeoAuditRoute
  '/app/$projectId': typeof AppProjectIdIndexRoute
  '/app/$projectId/reports/fanout': typeof AppProjectIdReportsFanoutRoute
  '/app/$projectId/reports/media': typeof AppProjectIdReportsMediaRoute
  '/app/$projectId/reports/reputation': typeof AppProjectIdReportsReputationRoute
  '/app/$projectId/reports/sentiment': typeof AppProjectIdReportsSentimentRoute
  '/app/$projectId/tools/annotations': typeof AppProjectIdToolsAnnotationsRoute
  '/app/$projectId/tools/research': typeof AppProjectIdToolsResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/generate-fixit': typeof ApiGenerateFixitRoute
  '/api/generate-insights': typeof ApiGenerateInsightsRoute
  '/api/generate-prompts': typeof ApiGeneratePromptsRoute
  '/api/process-jobs': typeof ApiProcessJobsRoute
  '/api/prompt-audit': typeof ApiPromptAuditRoute
  '/api/run-scheduled-prompts': typeof ApiRunScheduledPromptsRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
  '/api/llms-txt/$projectId': typeof ApiLlmsTxtProjectIdRoute
  '/app/$projectId/analytics': typeof AppProjectIdAnalyticsRoute
  '/app/$projectId/citations': typeof AppProjectIdCitationsRoute
  '/app/$projectId/competitors': typeof AppProjectIdCompetitorsRoute
  '/app/$projectId/content': typeof AppProjectIdContentRoute
  '/app/$projectId/insights': typeof AppProjectIdInsightsRoute
  '/app/$projectId/mentions': typeof AppProjectIdMentionsRoute
  '/app/$projectId/models': typeof AppProjectIdModelsRoute
  '/app/$projectId/prompts': typeof AppProjectIdPromptsRoute
  '/app/$projectId/rankings': typeof AppProjectIdRankingsRoute
  '/app/$projectId/reports': typeof AppProjectIdReportsRouteWithChildren
  '/app/$projectId/responses': typeof AppProjectIdResponsesRoute
  '/app/$projectId/seo-audit': typeof AppProjectIdSeoAuditRoute
  '/app/$projectId/': typeof AppProjectIdIndexRoute
  '/app/$projectId/reports/fanout': typeof AppProjectIdReportsFanoutRoute
  '/app/$projectId/reports/media': typeof AppProjectIdReportsMediaRoute
  '/app/$projectId/reports/reputation': typeof AppProjectIdReportsReputationRoute
  '/app/$projectId/reports/sentiment': typeof AppProjectIdReportsSentimentRoute
  '/app/$projectId/tools/annotations': typeof AppProjectIdToolsAnnotationsRoute
  '/app/$projectId/tools/research': typeof AppProjectIdToolsResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/app'
    | '/auth'
    | '/api/generate-fixit'
    | '/api/generate-insights'
    | '/api/generate-prompts'
    | '/api/process-jobs'
    | '/api/prompt-audit'
    | '/api/run-scheduled-prompts'
    | '/api/seo-audit'
    | '/app/alerts'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/integrations'
    | '/app/projects'
    | '/app/search'
    | '/app/settings'
    | '/app/team'
    | '/app/'
    | '/api/llms-txt/$projectId'
    | '/app/$projectId/analytics'
    | '/app/$projectId/citations'
    | '/app/$projectId/competitors'
    | '/app/$projectId/content'
    | '/app/$projectId/insights'
    | '/app/$projectId/mentions'
    | '/app/$projectId/models'
    | '/app/$projectId/prompts'
    | '/app/$projectId/rankings'
    | '/app/$projectId/reports'
    | '/app/$projectId/responses'
    | '/app/$projectId/seo-audit'
    | '/app/$projectId/'
    | '/app/$projectId/reports/fanout'
    | '/app/$projectId/reports/media'
    | '/app/$projectId/reports/reputation'
    | '/app/$projectId/reports/sentiment'
    | '/app/$projectId/tools/annotations'
    | '/app/$projectId/tools/research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/auth'
    | '/api/generate-fixit'
    | '/api/generate-insights'
    | '/api/generate-prompts'
    | '/api/process-jobs'
    | '/api/prompt-audit'
    | '/api/run-scheduled-prompts'
    | '/api/seo-audit'
    | '/app/alerts'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/integrations'
    | '/app/projects'
    | '/app/search'
    | '/app/settings'
    | '/app/team'
    | '/app'
    | '/api/llms-txt/$projectId'
    | '/app/$projectId/analytics'
    | '/app/$projectId/citations'
    | '/app/$projectId/competitors'
    | '/app/$projectId/content'
    | '/app/$projectId/insights'
    | '/app/$projectId/mentions'
    | '/app/$projectId/models'
    | '/app/$projectId/prompts'
    | '/app/$projectId/rankings'
    | '/app/$projectId/reports'
    | '/app/$projectId/responses'
    | '/app/$projectId/seo-audit'
    | '/app/$projectId'
    | '/app/$projectId/reports/fanout'
    | '/app/$projectId/reports/media'
    | '/app/$projectId/reports/reputation'
    | '/app/$projectId/reports/sentiment'
    | '/app/$projectId/tools/annotations'
    | '/app/$projectId/tools/research'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/app'
    | '/auth'
    | '/api/generate-fixit'
    | '/api/generate-insights'
    | '/api/generate-prompts'
    | '/api/process-jobs'
    | '/api/prompt-audit'
    | '/api/run-scheduled-prompts'
    | '/api/seo-audit'
    | '/app/alerts'
    | '/app/billing'
    | '/app/dashboard'
    | '/app/integrations'
    | '/app/projects'
    | '/app/search'
    | '/app/settings'
    | '/app/team'
    | '/app/'
    | '/api/llms-txt/$projectId'
    | '/app/$projectId/analytics'
    | '/app/$projectId/citations'
    | '/app/$projectId/competitors'
    | '/app/$projectId/content'
    | '/app/$projectId/insights'
    | '/app/$projectId/mentions'
    | '/app/$projectId/models'
    | '/app/$projectId/prompts'
    | '/app/$projectId/rankings'
    | '/app/$projectId/reports'
    | '/app/$projectId/responses'
    | '/app/$projectId/seo-audit'
    | '/app/$projectId/'
    | '/app/$projectId/reports/fanout'
    | '/app/$projectId/reports/media'
    | '/app/$projectId/reports/reputation'
    | '/app/$projectId/reports/sentiment'
    | '/app/$projectId/tools/annotations'
    | '/app/$projectId/tools/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiGenerateFixitRoute: typeof ApiGenerateFixitRoute
  ApiGenerateInsightsRoute: typeof ApiGenerateInsightsRoute
  ApiGeneratePromptsRoute: typeof ApiGeneratePromptsRoute
  ApiProcessJobsRoute: typeof ApiProcessJobsRoute
  ApiPromptAuditRoute: typeof ApiPromptAuditRoute
  ApiRunScheduledPromptsRoute: typeof ApiRunScheduledPromptsRoute
  ApiSeoAuditRoute: typeof ApiSeoAuditRoute
  ApiLlmsTxtProjectIdRoute: typeof ApiLlmsTxtProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/seo-audit': {
      id: '/api/seo-audit'
      path: '/api/seo-audit'
      fullPath: '/api/seo-audit'
      preLoaderRoute: typeof ApiSeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run-scheduled-prompts': {
      id: '/api/run-scheduled-prompts'
      path: '/api/run-scheduled-prompts'
      fullPath: '/api/run-scheduled-prompts'
      preLoaderRoute: typeof ApiRunScheduledPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prompt-audit': {
      id: '/api/prompt-audit'
      path: '/api/prompt-audit'
      fullPath: '/api/prompt-audit'
      preLoaderRoute: typeof ApiPromptAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-jobs': {
      id: '/api/process-jobs'
      path: '/api/process-jobs'
      fullPath: '/api/process-jobs'
      preLoaderRoute: typeof ApiProcessJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-prompts': {
      id: '/api/generate-prompts'
      path: '/api/generate-prompts'
      fullPath: '/api/generate-prompts'
      preLoaderRoute: typeof ApiGeneratePromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-insights': {
      id: '/api/generate-insights'
      path: '/api/generate-insights'
      fullPath: '/api/generate-insights'
      preLoaderRoute: typeof ApiGenerateInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-fixit': {
      id: '/api/generate-fixit'
      path: '/api/generate-fixit'
      fullPath: '/api/generate-fixit'
      preLoaderRoute: typeof ApiGenerateFixitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$projectId/': {
      id: '/app/$projectId/'
      path: '/$projectId'
      fullPath: '/app/$projectId/'
      preLoaderRoute: typeof AppProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/seo-audit': {
      id: '/app/$projectId/seo-audit'
      path: '/$projectId/seo-audit'
      fullPath: '/app/$projectId/seo-audit'
      preLoaderRoute: typeof AppProjectIdSeoAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/responses': {
      id: '/app/$projectId/responses'
      path: '/$projectId/responses'
      fullPath: '/app/$projectId/responses'
      preLoaderRoute: typeof AppProjectIdResponsesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/reports': {
      id: '/app/$projectId/reports'
      path: '/$projectId/reports'
      fullPath: '/app/$projectId/reports'
      preLoaderRoute: typeof AppProjectIdReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/rankings': {
      id: '/app/$projectId/rankings'
      path: '/$projectId/rankings'
      fullPath: '/app/$projectId/rankings'
      preLoaderRoute: typeof AppProjectIdRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/prompts': {
      id: '/app/$projectId/prompts'
      path: '/$projectId/prompts'
      fullPath: '/app/$projectId/prompts'
      preLoaderRoute: typeof AppProjectIdPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/models': {
      id: '/app/$projectId/models'
      path: '/$projectId/models'
      fullPath: '/app/$projectId/models'
      preLoaderRoute: typeof AppProjectIdModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/mentions': {
      id: '/app/$projectId/mentions'
      path: '/$projectId/mentions'
      fullPath: '/app/$projectId/mentions'
      preLoaderRoute: typeof AppProjectIdMentionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/insights': {
      id: '/app/$projectId/insights'
      path: '/$projectId/insights'
      fullPath: '/app/$projectId/insights'
      preLoaderRoute: typeof AppProjectIdInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/content': {
      id: '/app/$projectId/content'
      path: '/$projectId/content'
      fullPath: '/app/$projectId/content'
      preLoaderRoute: typeof AppProjectIdContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/competitors': {
      id: '/app/$projectId/competitors'
      path: '/$projectId/competitors'
      fullPath: '/app/$projectId/competitors'
      preLoaderRoute: typeof AppProjectIdCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/citations': {
      id: '/app/$projectId/citations'
      path: '/$projectId/citations'
      fullPath: '/app/$projectId/citations'
      preLoaderRoute: typeof AppProjectIdCitationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/analytics': {
      id: '/app/$projectId/analytics'
      path: '/$projectId/analytics'
      fullPath: '/app/$projectId/analytics'
      preLoaderRoute: typeof AppProjectIdAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/llms-txt/$projectId': {
      id: '/api/llms-txt/$projectId'
      path: '/api/llms-txt/$projectId'
      fullPath: '/api/llms-txt/$projectId'
      preLoaderRoute: typeof ApiLlmsTxtProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$projectId/tools/research': {
      id: '/app/$projectId/tools/research'
      path: '/$projectId/tools/research'
      fullPath: '/app/$projectId/tools/research'
      preLoaderRoute: typeof AppProjectIdToolsResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/tools/annotations': {
      id: '/app/$projectId/tools/annotations'
      path: '/$projectId/tools/annotations'
      fullPath: '/app/$projectId/tools/annotations'
      preLoaderRoute: typeof AppProjectIdToolsAnnotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/$projectId/reports/sentiment': {
      id: '/app/$projectId/reports/sentiment'
      path: '/sentiment'
      fullPath: '/app/$projectId/reports/sentiment'
      preLoaderRoute: typeof AppProjectIdReportsSentimentRouteImport
      parentRoute: typeof AppProjectIdReportsRoute
    }
    '/app/$projectId/reports/reputation': {
      id: '/app/$projectId/reports/reputation'
      path: '/reputation'
      fullPath: '/app/$projectId/reports/reputation'
      preLoaderRoute: typeof AppProjectIdReportsReputationRouteImport
      parentRoute: typeof AppProjectIdReportsRoute
    }
    '/app/$projectId/reports/media': {
      id: '/app/$projectId/reports/media'
      path: '/media'
      fullPath: '/app/$projectId/reports/media'
      preLoaderRoute: typeof AppProjectIdReportsMediaRouteImport
      parentRoute: typeof AppProjectIdReportsRoute
    }
    '/app/$projectId/reports/fanout': {
      id: '/app/$projectId/reports/fanout'
      path: '/fanout'
      fullPath: '/app/$projectId/reports/fanout'
      preLoaderRoute: typeof AppProjectIdReportsFanoutRouteImport
      parentRoute: typeof AppProjectIdReportsRoute
    }
  }
}

interface AppProjectIdReportsRouteChildren {
  AppProjectIdReportsFanoutRoute: typeof AppProjectIdReportsFanoutRoute
  AppProjectIdReportsMediaRoute: typeof AppProjectIdReportsMediaRoute
  AppProjectIdReportsReputationRoute: typeof AppProjectIdReportsReputationRoute
  AppProjectIdReportsSentimentRoute: typeof AppProjectIdReportsSentimentRoute
}

const AppProjectIdReportsRouteChildren: AppProjectIdReportsRouteChildren = {
  AppProjectIdReportsFanoutRoute: AppProjectIdReportsFanoutRoute,
  AppProjectIdReportsMediaRoute: AppProjectIdReportsMediaRoute,
  AppProjectIdReportsReputationRoute: AppProjectIdReportsReputationRoute,
  AppProjectIdReportsSentimentRoute: AppProjectIdReportsSentimentRoute,
}

const AppProjectIdReportsRouteWithChildren =
  AppProjectIdReportsRoute._addFileChildren(AppProjectIdReportsRouteChildren)

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectIdAnalyticsRoute: typeof AppProjectIdAnalyticsRoute
  AppProjectIdCitationsRoute: typeof AppProjectIdCitationsRoute
  AppProjectIdCompetitorsRoute: typeof AppProjectIdCompetitorsRoute
  AppProjectIdContentRoute: typeof AppProjectIdContentRoute
  AppProjectIdInsightsRoute: typeof AppProjectIdInsightsRoute
  AppProjectIdMentionsRoute: typeof AppProjectIdMentionsRoute
  AppProjectIdModelsRoute: typeof AppProjectIdModelsRoute
  AppProjectIdPromptsRoute: typeof AppProjectIdPromptsRoute
  AppProjectIdRankingsRoute: typeof AppProjectIdRankingsRoute
  AppProjectIdReportsRoute: typeof AppProjectIdReportsRouteWithChildren
  AppProjectIdResponsesRoute: typeof AppProjectIdResponsesRoute
  AppProjectIdSeoAuditRoute: typeof AppProjectIdSeoAuditRoute
  AppProjectIdIndexRoute: typeof AppProjectIdIndexRoute
  AppProjectIdToolsAnnotationsRoute: typeof AppProjectIdToolsAnnotationsRoute
  AppProjectIdToolsResearchRoute: typeof AppProjectIdToolsResearchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppBillingRoute: AppBillingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectIdAnalyticsRoute: AppProjectIdAnalyticsRoute,
  AppProjectIdCitationsRoute: AppProjectIdCitationsRoute,
  AppProjectIdCompetitorsRoute: AppProjectIdCompetitorsRoute,
  AppProjectIdContentRoute: AppProjectIdContentRoute,
  AppProjectIdInsightsRoute: AppProjectIdInsightsRoute,
  AppProjectIdMentionsRoute: AppProjectIdMentionsRoute,
  AppProjectIdModelsRoute: AppProjectIdModelsRoute,
  AppProjectIdPromptsRoute: AppProjectIdPromptsRoute,
  AppProjectIdRankingsRoute: AppProjectIdRankingsRoute,
  AppProjectIdReportsRoute: AppProjectIdReportsRouteWithChildren,
  AppProjectIdResponsesRoute: AppProjectIdResponsesRoute,
  AppProjectIdSeoAuditRoute: AppProjectIdSeoAuditRoute,
  AppProjectIdIndexRoute: AppProjectIdIndexRoute,
  AppProjectIdToolsAnnotationsRoute: AppProjectIdToolsAnnotationsRoute,
  AppProjectIdToolsResearchRoute: AppProjectIdToolsResearchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiGenerateFixitRoute: ApiGenerateFixitRoute,
  ApiGenerateInsightsRoute: ApiGenerateInsightsRoute,
  ApiGeneratePromptsRoute: ApiGeneratePromptsRoute,
  ApiProcessJobsRoute: ApiProcessJobsRoute,
  ApiPromptAuditRoute: ApiPromptAuditRoute,
  ApiRunScheduledPromptsRoute: ApiRunScheduledPromptsRoute,
  ApiSeoAuditRoute: ApiSeoAuditRoute,
  ApiLlmsTxtProjectIdRoute: ApiLlmsTxtProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
