/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSeoAuditRouteImport } from './routes/app.seo-audit'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRankingsRouteImport } from './routes/app.rankings'
import { Route as AppPromptsRouteImport } from './routes/app.prompts'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppModelsRouteImport } from './routes/app.models'
import { Route as AppMentionsRouteImport } from './routes/app.mentions'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCompetitorsRouteImport } from './routes/app.competitors'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as ApiSeoAuditRouteImport } from './routes/api.seo-audit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoAuditRoute = AppSeoAuditRouteImport.update({
  id: '/seo-audit',
  path: '/seo-audit',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptsRoute = AppPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppMentionsRoute = AppMentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const ApiSeoAuditRoute = ApiSeoAuditRouteImport.update({
  id: '/api/seo-audit',
  path: '/api/seo-audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/mentions': typeof AppMentionsRoute
  '/app/models': typeof AppModelsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/seo-audit': typeof AppSeoAuditRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/mentions': typeof AppMentionsRoute
  '/app/models': typeof AppModelsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/seo-audit': typeof AppSeoAuditRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/seo-audit': typeof ApiSeoAuditRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/mentions': typeof AppMentionsRoute
  '/app/models': typeof AppModelsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/prompts': typeof AppPromptsRoute
  '/app/rankings': typeof AppRankingsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/seo-audit': typeof AppSeoAuditRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/team': typeof AppTeamRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/api/seo-audit'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/billing'
    | '/app/competitors'
    | '/app/dashboard'
    | '/app/integrations'
    | '/app/mentions'
    | '/app/models'
    | '/app/projects'
    | '/app/prompts'
    | '/app/rankings'
    | '/app/reports'
    | '/app/seo-audit'
    | '/app/settings'
    | '/app/team'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/seo-audit'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/billing'
    | '/app/competitors'
    | '/app/dashboard'
    | '/app/integrations'
    | '/app/mentions'
    | '/app/models'
    | '/app/projects'
    | '/app/prompts'
    | '/app/rankings'
    | '/app/reports'
    | '/app/seo-audit'
    | '/app/settings'
    | '/app/team'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/api/seo-audit'
    | '/app/alerts'
    | '/app/analytics'
    | '/app/billing'
    | '/app/competitors'
    | '/app/dashboard'
    | '/app/integrations'
    | '/app/mentions'
    | '/app/models'
    | '/app/projects'
    | '/app/prompts'
    | '/app/rankings'
    | '/app/reports'
    | '/app/seo-audit'
    | '/app/settings'
    | '/app/team'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiSeoAuditRoute: typeof ApiSeoAuditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seo-audit': {
      id: '/app/seo-audit'
      path: '/seo-audit'
      fullPath: '/app/seo-audit'
      preLoaderRoute: typeof AppSeoAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rankings': {
      id: '/app/rankings'
      path: '/rankings'
      fullPath: '/app/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prompts': {
      id: '/app/prompts'
      path: '/prompts'
      fullPath: '/app/prompts'
      preLoaderRoute: typeof AppPromptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/models': {
      id: '/app/models'
      path: '/models'
      fullPath: '/app/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentions': {
      id: '/app/mentions'
      path: '/mentions'
      fullPath: '/app/mentions'
      preLoaderRoute: typeof AppMentionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitors': {
      id: '/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/seo-audit': {
      id: '/api/seo-audit'
      path: '/api/seo-audit'
      fullPath: '/api/seo-audit'
      preLoaderRoute: typeof ApiSeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppMentionsRoute: typeof AppMentionsRoute
  AppModelsRoute: typeof AppModelsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppPromptsRoute: typeof AppPromptsRoute
  AppRankingsRoute: typeof AppRankingsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSeoAuditRoute: typeof AppSeoAuditRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBillingRoute: AppBillingRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppMentionsRoute: AppMentionsRoute,
  AppModelsRoute: AppModelsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppPromptsRoute: AppPromptsRoute,
  AppRankingsRoute: AppRankingsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSeoAuditRoute: AppSeoAuditRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiSeoAuditRoute: ApiSeoAuditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
